### ISSUE TITLE
leading zeros when using KanjizeStyle.FLAT gives an error

### ISSUE THREAD

**Issue by echan00** [nagataaaas/Kanjize#8]
Amazing library. Surprised to find a bug:

Current:
```
>>> number2kanji(01, config=KanjizeConfiguration(style=KanjizeStyle.FLAT)))
  File "<stdin>", line 1
    number2kanji(01, config=KanjizeConfiguration(style=KanjizeStyle.FLAT)))
                 ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers

```
Expected:
```
print(number2kanji(01, config=KanjizeConfiguration(style=KanjizeStyle.FLAT)))
    # 〇一

```

**Comment by nagataaaas** [comment]
Thanks for reporting this behavior.

However, this is not a bug of this library.
In Python, you cannot start numbers with zero as the error says.

This library is only created to convert valid kanji string into Python integer and vice versa.

Since `01` is not valid Python integer literal, what you want to achieve is not supported.

If you want to convert each digit of number into corresponding kanji, you can achive it with code below

```python
kanjize_trans_table = str.maketrans({k: v for k, v in 
zip('0123456789', '〇一二三四五六七八九')})

def kanjize(number_text: str) -> str:
    return number_text.translate(kanjize_trans_table)
	
print(kanjize('01'))  # 〇一
```

**Comment by echan00** [comment]
No problem, I'm not sure pointing at Python is a real resolution here. But I resolved the issue by adding a digit in front of the string and then removing the first character after the conversion. 

Many thanks for the quick response.
